### ISSUE TITLE
DockArticulate.md

### ISSUE THREAD

**Issue by jeetee** [BernardGreenberg/MuseScorePlugins#7]
Since 3.4.0 (May 2020) TempoChanges should no longer be closing off dock plugins. (see https://github.com/jeetee/MuseScore_TempoChanges/releases/tag/3.4.0 )
Would you be so kind as to verify this behavior and then update your readme accordingly? (but keep the warning in there for not all plugins out there have been fixed in that respect)

**Comment by BernardGreenberg** [comment]
I will get to it today or tomorrow, thanks.
________________________________

**Comment by BernardGreenberg** [comment]
I have verified that it does not close Dock Articulate..  I will fix my documentation.
________________________________

**Comment by BernardGreenberg** [comment]
New TempoChanges behavior verified, documentation updated.

**Comment by jeetee** [comment]
Speedy service :)

**Comment by BernardGreenberg** [comment]
Would be nice if "reload plugins" didn't erase all shortcuts.
________________________________
